id: P48D8FC55
initial_creation_type: input
source_metadata:
  title: Sickness and Healing
  language: bo
  description: 'Lotsawa House presents the following texts as part of our Sickness
    and Healing Series:'
  volume:
    f0c7ff6a6a774c6c9e5060a40e48a7af:
      title: Three Ways of Bringing Sickness onto the Path
      parent: Advice
    08082aae90f54dc1a939b28580c2ab69:
      title: How to Transform Sickness and Other Circumstances
      parent: Advice
    a7928ba898e34b9e889aa8d74b570fd4:
      title: The Universal Medicine for Healing All Ills
      parent: Advice
    a1df1b742c974eb08eabb9b80df0994c:
      title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
      parent: Mantras
    15e18bd473aa469686d0db77ea73f7a4:
      title: Wrathful Guru Mantra Visualization
      parent: Mantras
    f990398ef1c344e883f86c1a6806da8c:
      title: Dhāraṇī of Goddess Parṇaśavarī
      parent: Practices
    4b2df5448cba4c048808e36f4e90adc3:
      title: Daily Practice of Guru Rinpoche, Buddha of Medicine
      parent: Practices
    f6fe7930edc443d9bf843830c171f918:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Practices
    cda07da4a55d4275bdb4e219f6095ca8:
      title: Daily Practice of Dorje Gotrab
      parent: Practices
    bdd8c983cd5a4f05b4f964f2a1c61932:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Practices
    c649ca49808d46539c3d0b189736c3d0:
      title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
      parent: Practices
    d9a5c9a58c8d4ed4badbb6342b27467a:
      title: 'Zabchema: Profound Cure, The Practice of Bhaiṣajya-Guru, Lord of Physicians'
      parent: Practices
    13d987af076a47babf89636114d5a435:
      title: Acala Sādhana
      parent: Practices
    872518b5ed4f4cb5b918996c8ed76baa:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Practices
    b767cbe9155f4298b72e117587ad3024:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Prayers
created_at: '2022-03-01T05:47:13.664122'
last_modified_at: '2022-03-01T05:47:13.664125'
statistics:
  total_words: 5033
  total_non_words: 956
quality:
  non_words_ratio: 0.19
